name: vitaguard_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3  
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.2.3
  url_launcher: ^6.1.10
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  logger: ^2.5.0
  image_picker: ^1.1.2
  flutter_riverpod: any
  riverpod_annotation: any
  drift: any
  drift_flutter: any
  flutter_local_notifications: ^20.0.0
  image: any
  supabase_flutter: ^2.5.6
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.5
  lucide_icons: ^0.257.0
  flutter_markdown_plus: ^1.0.7
  cached_network_image: ^3.4.1
  tflite_flutter: ^0.12.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  drift_dev: any
  riverpod_generator: any
  flutter_launcher_icons: "^0.14.4"  
  freezed: ^3.2.5
  json_serializable: ^6.13.0

# ✅ بلوك مستقل في الـ root (مش جوه dev_dependencies)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo/لوجوو1.jpg 1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/cover/
    - assets/Logo/
    - assets/Logo/Vita Guard 2.png
    - assets/PNG/
    - assets/SVG/
    - assets/models/
    - assets/sounds/

  fonts:
    - family: WixMadeforDisplay
      fonts:
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-ExtraBold.ttf
          weight: 800
