name: vitaguard_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.2.3
  url_launcher: ^6.1.10
  intl: ^0.19.0   # ✅ تمت الإضافة
  connectivity_plus: ^6.1.1
  logger: ^2.5.0
  image_picker: ^1.1.2
  flutter_riverpod: any
  image: any
  tflite_flutter: any
  # Firebase core + plugins (version pinned by pub resolver via 'any')
  firebase_core: any
  firebase_auth: any
  firebase_ai: any
  firebase_analytics: any
  firebase_app_check: any
  cloud_firestore: any
  cloud_functions: any
  firebase_messaging: any
  firebase_storage: any
  firebase_crashlytics: any
  firebase_data_connect: any
  firebase_dynamic_links: any
  firebase_in_app_messaging: any
  firebase_app_installations: any
  firebase_ml_model_downloader: any
  firebase_performance: any
  firebase_database: any
  firebase_remote_config: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cover/
    - assets/Logo/
    - assets/PNG/
    - assets/SVG/
    - assets/models/

  fonts:   # ✅ لازم تكون جوه flutter
    - family: WixMadeforDisplay
      fonts:
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/WixMadeforDisplay/WixMadeforDisplay-ExtraBold.ttf
          weight: 800
