// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTyteK7n5ny6bq8Hv_DiJ0QjnC74HV74',
    appId: '1:741221505562:web:fd36088cd45a94861c8fa3',
    messagingSenderId: '741221505562',
    projectId: 'vitaguard-prod',
    authDomain: 'vitaguard-prod.firebaseapp.com',
    storageBucket: 'vitaguard-prod.firebasestorage.app',
    measurementId: 'G-TT6SXB5JLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDi5Oi9nlAir_x5klGUcupbEgUXN1I54',
    appId: '1:741221505562:android:5d657c65d95e3b811c8fa3',
    messagingSenderId: '741221505562',
    projectId: 'vitaguard-prod',
    storageBucket: 'vitaguard-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOinWOt-6km2KlzixLaOocMok3eippQmU',
    appId: '1:741221505562:ios:1934a2676e8f4db61c8fa3',
    messagingSenderId: '741221505562',
    projectId: 'vitaguard-prod',
    storageBucket: 'vitaguard-prod.firebasestorage.app',
    iosBundleId: 'com.example.vitaguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOinWOt-6km2KlzixLaOocMok3eippQmU',
    appId: '1:741221505562:ios:1934a2676e8f4db61c8fa3',
    messagingSenderId: '741221505562',
    projectId: 'vitaguard-prod',
    storageBucket: 'vitaguard-prod.firebasestorage.app',
    iosBundleId: 'com.example.vitaguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJTyteK7n5ny6bq8Hv_DiJ0QjnC74HV74',
    appId: '1:741221505562:web:fb7ca88ad4c41be21c8fa3',
    messagingSenderId: '741221505562',
    projectId: 'vitaguard-prod',
    authDomain: 'vitaguard-prod.firebaseapp.com',
    storageBucket: 'vitaguard-prod.firebasestorage.app',
    measurementId: 'G-TRSSZP5T3M',
  );
}
