"""verification_and_uploads

Revision ID: 59872433a5a9
Revises: 
Create Date: 2026-03-12 15:21:35.990615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59872433a5a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_medical_documents_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_documents'))
    )
    with op.batch_alter_table('companion_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_companion_profiles_user_id'), ['user_id'])

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_profiles_user_id'), ['user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_doctor_profiles_reviewed_by_users'), 'users', ['reviewed_by'], ['id'])

    with op.batch_alter_table('facility_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('facility_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_facility_profiles_user_id'), ['user_id'])

    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_patient_profiles_companion_code'), ['companion_code'])
        batch_op.create_unique_constraint(batch_op.f('uq_patient_profiles_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patient_profiles_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_patient_profiles_companion_code'), type_='unique')

    with op.batch_alter_table('facility_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_facility_profiles_user_id'), type_='unique')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('facility_offers', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctor_profiles_reviewed_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_doctor_profiles_user_id'), type_='unique')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('id_card_image_url')

    with op.batch_alter_table('companion_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_companion_profiles_user_id'), type_='unique')

    op.drop_table('medical_documents')
    # ### end Alembic commands ###
